package co.edu.uniquindio.compiladores.logica.lexico

enum class Categoria {

    IDENTIFICADOR_VARIABLE, IDENTIFICADOR_CLASE, IDENTIFICADOR_METODO, PAL_RESERVADA, ENTERO, REAL, OPERADOR_ARITMETICO,
    OPERADOR_LOGICO, OPERADOR_ASIGNACION, OPERADOR_INCREMENTO, OPERADOR_DECREMENTO, OPERADOR_RELACIONAL,
    AGRUPADOR_DERECHO, AGRUPADOR_IZQUIERDO, FINAL_SENTENCIA, SEPARADOR,COMENTARIO_LINEA, COMENTARIO_BLOQUE, FIN_CODIGO, CADENA,
    CARACTER_SINGULAR, NO_RECONOCIDO

}